// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

// GetVersion defines model for GetVersion.
type GetVersion struct {
	Version string `json:"version"`
}
