// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: awesome.proto

package awesome

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionV1Request) Reset() {
	*x = GetVersionV1Request{}
	mi := &file_awesome_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionV1Request) ProtoMessage() {}

func (x *GetVersionV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_awesome_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionV1Request.ProtoReflect.Descriptor instead.
func (*GetVersionV1Request) Descriptor() ([]byte, []int) {
	return file_awesome_proto_rawDescGZIP(), []int{0}
}

type GetVersionV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionV1Response) Reset() {
	*x = GetVersionV1Response{}
	mi := &file_awesome_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionV1Response) ProtoMessage() {}

func (x *GetVersionV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_awesome_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionV1Response.ProtoReflect.Descriptor instead.
func (*GetVersionV1Response) Descriptor() ([]byte, []int) {
	return file_awesome_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionV1Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_awesome_proto protoreflect.FileDescriptor

const file_awesome_proto_rawDesc = "" +
	"\n" +
	"\rawesome.proto\x12\aawesome\"\x15\n" +
	"\x13GetVersionV1Request\"0\n" +
	"\x14GetVersionV1Response\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2V\n" +
	"\aAwesome\x12K\n" +
	"\fGetVersionV1\x12\x1c.awesome.GetVersionV1Request\x1a\x1d.awesome.GetVersionV1ResponseB.Z,github.com/vendor116/awesome/pkg/api/awesomeb\x06proto3"

var (
	file_awesome_proto_rawDescOnce sync.Once
	file_awesome_proto_rawDescData []byte
)

func file_awesome_proto_rawDescGZIP() []byte {
	file_awesome_proto_rawDescOnce.Do(func() {
		file_awesome_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_awesome_proto_rawDesc), len(file_awesome_proto_rawDesc)))
	})
	return file_awesome_proto_rawDescData
}

var file_awesome_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_awesome_proto_goTypes = []any{
	(*GetVersionV1Request)(nil),  // 0: awesome.GetVersionV1Request
	(*GetVersionV1Response)(nil), // 1: awesome.GetVersionV1Response
}
var file_awesome_proto_depIdxs = []int32{
	0, // 0: awesome.Awesome.GetVersionV1:input_type -> awesome.GetVersionV1Request
	1, // 1: awesome.Awesome.GetVersionV1:output_type -> awesome.GetVersionV1Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_awesome_proto_init() }
func file_awesome_proto_init() {
	if File_awesome_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_awesome_proto_rawDesc), len(file_awesome_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_awesome_proto_goTypes,
		DependencyIndexes: file_awesome_proto_depIdxs,
		MessageInfos:      file_awesome_proto_msgTypes,
	}.Build()
	File_awesome_proto = out.File
	file_awesome_proto_goTypes = nil
	file_awesome_proto_depIdxs = nil
}
