// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: awesome.proto

package awesome

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Awesome_GetVersionV1_FullMethodName = "/awesome.Awesome/GetVersionV1"
)

// AwesomeClient is the client API for Awesome service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AwesomeClient interface {
	GetVersionV1(ctx context.Context, in *GetVersionV1Request, opts ...grpc.CallOption) (*GetVersionV1Response, error)
}

type awesomeClient struct {
	cc grpc.ClientConnInterface
}

func NewAwesomeClient(cc grpc.ClientConnInterface) AwesomeClient {
	return &awesomeClient{cc}
}

func (c *awesomeClient) GetVersionV1(ctx context.Context, in *GetVersionV1Request, opts ...grpc.CallOption) (*GetVersionV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionV1Response)
	err := c.cc.Invoke(ctx, Awesome_GetVersionV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AwesomeServer is the server API for Awesome service.
// All implementations must embed UnimplementedAwesomeServer
// for forward compatibility.
type AwesomeServer interface {
	GetVersionV1(context.Context, *GetVersionV1Request) (*GetVersionV1Response, error)
	mustEmbedUnimplementedAwesomeServer()
}

// UnimplementedAwesomeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAwesomeServer struct{}

func (UnimplementedAwesomeServer) GetVersionV1(context.Context, *GetVersionV1Request) (*GetVersionV1Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersionV1 not implemented")
}
func (UnimplementedAwesomeServer) mustEmbedUnimplementedAwesomeServer() {}
func (UnimplementedAwesomeServer) testEmbeddedByValue()                 {}

// UnsafeAwesomeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AwesomeServer will
// result in compilation errors.
type UnsafeAwesomeServer interface {
	mustEmbedUnimplementedAwesomeServer()
}

func RegisterAwesomeServer(s grpc.ServiceRegistrar, srv AwesomeServer) {
	// If the following call panics, it indicates UnimplementedAwesomeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Awesome_ServiceDesc, srv)
}

func _Awesome_GetVersionV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwesomeServer).GetVersionV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Awesome_GetVersionV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwesomeServer).GetVersionV1(ctx, req.(*GetVersionV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Awesome_ServiceDesc is the grpc.ServiceDesc for Awesome service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Awesome_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "awesome.Awesome",
	HandlerType: (*AwesomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersionV1",
			Handler:    _Awesome_GetVersionV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "awesome.proto",
}
