// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package openapi

// GetVersion defines model for GetVersion.
type GetVersion struct {
	Version string `json:"version"`
}
